version: "3.1"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
  mysql:
        image: mysql:5.7 
        container_name: mysql
        restart: always 
        volumes:
            - /var/lib/mysql
        ports:
            - "3306:3306" 
        environment:
            - MYSQL_DATABASE=alfa
            - MYSQL_ROOT_PASSWORD=root