version: "3.1"

services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    command: bash -c "php -S localhost:8080 -t public/"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=alfa
      - MYSQL_ROOT_PASSWORD=root
    network_mode: host
